### ISSUE TITLE
SQLAlchemy version heck causing runner startup failure?

### ISSUE THREAD

**Issue by dkegel-fastly** [openappsec/waf-comparison-project#7]
Symptom:
```
$ python3 runner.py 
...
  DEBUG    | All tests have been successfully completed.
Traceback (most recent call last):
  File "runner.py", line 158, in <module>
    main()
  File "runner.py", line 151, in main
    check_engine_connection()
  File "runner.py", line 22, in check_engine_connection
    _ = pd.read_sql_query("SELECT 1", engine)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/io/sql.py", line 435, in read_sql_query
    pandas_sql = pandasSQL_builder(con)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/io/sql.py", line 788, in pandasSQL_builder
    return SQLDatabase(con, schema=schema, meta=meta)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/io/sql.py", line 1410, in __init__
    meta = MetaData(self.connectable, schema=schema)
TypeError: __init__() got multiple values for argument 'schema'
```

Workaround:
```
$ python3 -m pip install sqlalchemy==1.4.46
```

h/t https://stackoverflow.com/questions/75282511/df-to-table-throw-error-typeerror-init-got-multiple-values-for-argument

Perhaps the reqirements.txt could be more specific about sqlalchemy major version...?

**Comment by jackneer** [comment]
@Boris-Rozenfeld I'd add the version number to requirements.txt or you are looking for other approach.

**Comment by Boris-Rozenfeld** [comment]
Hey @dkegel-fastly , @jackneer 

Thank you for your feedback. Since pandas changed its integration with SQLAlchemy and sqlite3 after version 2.2.0, I refactored the database connection to work directly with SQLite using sqlite3 instead of SQLAlchemy.

You can review the relevant commit here: [Refactor database connection from SQLAlchemy to SQLite](https://github.com/openappsec/waf-comparison-project/commit/e72216b35f6585e1322c2ea47bb14545de85d134)
